### ISSUE TITLE
Sentinel randomized tx time

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#112]
As a sentinel operator acting as pleb, I don't want transactions failing because other sentinels tried to do the same at the same time and happened to have their tx included before.  

Pleb liquidations should be scheduled with a random component added. Instead of sending a tx right at the estimation point, the application should add a randomized delay ranging between 0 and x seconds. x should be a user configurable parameter which defaults to 10 minutes (that's imo a value which should do the job for L2s too). If the user sets it to 0, the behaviour is like now (no waiting).  
Before the actual tx sending, the application needs to make sure that the relevant stream is still open and that gas parameters allow sending (`block.baseFeePerGas` < user set gas price limit).

**Comment by ngmachado** [comment]
This is more a discussion than one specific issue. https://github.com/didi can we migrate to a specific discussion?

**Comment by ngmachado** [comment]
We can reopen this question if needed.
