### ISSUE TITLE
Automated snapshot creation

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#113]
**Create snapshots available on IPFS:**
* fetch the latest sentinel release and `npm ci`
* for every configured network:
  * run `npm build-snap`
  * add the created DB file to IPFS (`ipfs --api <api addr> add <file>`)
  * get hash/CID of uploaded file
  * publish (or push) hash/CID
* (maybe) somehow notify about new snapshots

**Point sentinels repo to latest snapshots:**
Option push:  
Have a local copy of the git repo, modify `manifest.json` with the updated hashes/CIDs, commit to a branch, push to GH and create a PR on GB.

Option pull a:
Have a github action (which trigger?) pull the latest snapshot hashes/CIDs and update `manifest.json` accordingly.

Option pull b:
Let a git hook pull the latest snapshot hashes/CIDs and update `manifest.json` accordingly.

For the pull options, we also need a way for how the _repo updating agent_ can access the data (hashes/CIDs) provided by the _snapshot creation agent_. If running on a dev machine, it could be just an `ssh <machine> "cat file" ...`. Else (e.g. GH action) it could be any of a dedicated API/webservice provided by the creation agent, DNS entries, ENS (just kidding - as long as no L2 ENS), IPNS (bad past experiences...), ...?

**Comment by d10r** [comment]
favorite option:  
Push: after snapshot generation, the snapshot creation agent triggers a GH action via webhook. That action shall update manifest.json in a dedicated branch and create a PR if none exists currently.  
Additionally, that GH action shall verify the provided snapshot hashes/CIDs, e.g. with `npm run verify-snapshot <network>`.

**Comment by d10r** [comment]
@ngmachado example for IPFS pinning:

```
sentinel@buck-1:~/superfluid-sentinel/snapshots$ ipfs --api /ip4/65.21.152.182/tcp/5001 add snapshot_4_1643374733.sqlite.gz
added QmaJWnQ9K3Y6e75szA3itYGd5MRwxetpEJHr4pseEEUEU1 snapshot_4_1643374733.sqlite.gz
 2.06 MiB / 2.06 MiB [=============================================================================================================================================================================================] 100.00%
```

The IPFS API addr should be configurable.

If you want to use that API from other machines than buck-1, let me know - need to add permission to its firewall then (if open to the Internet, anybody could upload stuff there).

**Comment by ngmachado** [comment]
From the last PR the `verify-snapshot` was rename to `test-sync`

**Comment by hellwolf** [comment]
We can document the process in the process section of https://github.com/superfluid-finance/superfluid-sentinel/wiki/About-Fastsync
