### ISSUE TITLE
[SENTINEL][DOCS] - Add information on how to upgrade sentinel to a new release 

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/superfluid-sentinel#139]
__Add information on how to upgrade sentinel to a new release__

- Docker: get new image version (pull from repo)
- Local: use git to get last version.

I'm missing something?

**Comment by hellwolf** [comment]
> I'm missing something?

Missing next step.

**Comment by d10r** [comment]
can imo be closed, is now part of the readme [here](https://github.com/superfluid-finance/superfluid-sentinel?tab=readme-ov-file#update) and [here](https://github.com/superfluid-finance/superfluid-sentinel?tab=readme-ov-file#update-1)
