### ISSUE TITLE
Polish snapshot creation tooling and add to repo

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#159]
On sentinel@buck-1 there's more automation tooling for snapshot creation.

A cronjob executes generate-all.sh which does:
* for each network:
  * run `scripts/buildSnapshot.js`
  * push snapshot file to an IPFS node
* generate a new manifest (ad-hoc script `generateManifest.js`)
* create a github PR with the new manifest

To be done:
* modularize such that it's useful for individual sentinel runners too (e.g. ability to run without the PR step)
* provide entry point for single network
* take all credentials and custom paths/names via ENV vars
* use medadata
* add to sentinel repo

**Comment by ngmachado** [comment]
The PR should be made to metadata repo and not this repo.

#160

**Comment by ngmachado** [comment]
After talking with @Didi, the snapshot hashes should be committed to this repo. Not useful not any other superfluid system. Everything else on manifest should be consume from metadata repo.

**Comment by d10r** [comment]
fyi I have worked on _modularize such that it's useful for individual sentinel runners too (e.g. ability to run without the PR step)_ , see `buck-1:/home/sentinel/generate-all.sh` (there's a backup of the previous version in case you don't like all changes).

The cronjob is currently set to monthly, but won't succeed bcs GH PR creation interactively asks for a password, couldn't figure out how to prevent that.

**Comment by ngmachado** [comment]
We solve this credential problem in our last pair-programming.

@d10r can we close this one?
