### ISSUE TITLE
Issue - Reserving more Gas limit than really needed.

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/superfluid-sentinel#162]
https://github.com/superfluid-finance/superfluid-sentinel/blob/c4ed3740cea8adfbfb0c71a2cc9c008856caaa85/src/transaction/gas.js#L13

should be one of two:

- add 20% to result
- result = 120% of original estimation

**Comment by d10r** [comment]
this is a tx with that line commented out: https://polygonscan.com/tx/0xd1ada990716f4ed4a704b6ec4cb9ea4205a48b7573e32e040f43604130181011

Looks like web3.js already adds a 20% buffer itself.

**Comment by d10r** [comment]
maybe not always enough, see e.g. https://polygonscan.com/tx/0x3beabe2beb68b00e8e532697d67de8a385aad0529ea5c805d3fccdf224f8e6cb

Switched to +20%

**Comment by d10r** [comment]
With +20%, the max. relative use of the given gas budget I could spot was ~67% - looks like without any manual buffer, the limit was just slightly too small. With +5% (current setting) it seems to never run out of gas: https://polygonscan.com/address/0xC20a5455035Ab593682Cf9b9916b9407cc9e47f3
