### ISSUE TITLE
warn if connected to an unsupported network

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#173]
```
sentinel_1  | 2023-03-07T00:22:50.049Z - info: Client connecting to RPC...
sentinel_1  | 2023-03-07T00:22:50.057Z - info: Client connected to RPC
sentinel_1  | 2023-03-07T00:22:50.420Z - error: App.start(): TypeError: Cannot read property 'epoch' of undefined
```

This happens when configuring an RPC not matching any network in the manifest file.
Should print an error message telling it's connected to an unsupported network, printing the chainId.

**Comment by ngmachado** [comment]
In this case the sentinel should throw and error, log it and exit.

There is nothing we can do without contracts as entry points.
