### ISSUE TITLE
Dust protection for Sentinels

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/superfluid-sentinel#213]
Snipe them at low gas prices.

**Comment by ngmachado** [comment]
The core protection feature in this PR.

As an optional feature, operators can supply a threshold file that specifies token addresses and corresponding amounts, which will be used to determine liquidation inclusion.

In cases where the threshold file is not provided, the system will fall back to its default behavior. Additionally, if a threshold file is supplied but does not include information for all tokens, any missing tokens will also revert to the default behavior.

Please note that we are still testing and this can be changed before merging.
