### ISSUE TITLE
Wrong Variable Initialization

### ISSUE THREAD

**Issue by msoni89** [superfluid-finance/superfluid-sentinel#218]
**Describe the bug:**
The initialization of variable **keepTrying = 10** is wrong. 

**Environment:**
Master branch

**Expected behavior:**
it should be initialized with 0 or 1 (like other places), code will exit on the first exception without retrying.

**Actual behavior:**
Wrong initialization of keepTrying variable.

**Screenshots:**
![image](https://github.com/superfluid-finance/superfluid-sentinel/assets/65469737/d4a8eced-05d8-472b-8a30-163c92989207)

**Comment by ngmachado** [comment]
Thank you for the report.

The variable is intentional set to be 10 (the default retries) to exist in the case of error.
Will review this and change the code because is confusing and don't show why we hardcode it.
