### ISSUE TITLE
[SENTINEL] [GDA] Test Sentinel on Testnet

### ISSUE THREAD

**Issue by philipandersson** [superfluid-finance/superfluid-sentinel#237]
## Test Plan (Elvijs not proved yet)

- Generate streams & distributions on testnets
  - Map out test scenarios
    - [x] Sentinel should pick up new GDA streams
    - [x] GDA stream getting liquidated
    - [x] GDA stream getting liquidated after modifying the flow rate
    - [x] GDA stream getting liquidated after modifying the units 
    - [x] GDA stream getting liquidated after a GDA distribution
    - [x] CFA stream + GDA stream getting liquidated
    - [x] CFA stream getting liquidated after a GDA distribution
  - Randomized tests (fuzzing?)
- Feature + Regression test, run new version on mainnet to see we are not breaking anything

### Acceptance criteria.

- [x] Old agent (0.x.y) should still work, albeit not supporting GDA feture.
- New agent (1.x.y) should work for all networks
  - [x] for testnets that has GDA feature, there should be observable GDA liquidations.
  - [x] for other testnets and mainnets, new agent should work as expected too.

**Comment by philipandersson** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/superfluid-sentinel/237?planning-poker) with Zenhub @d10r @ngmachado

**Comment by vmichalik** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Protocol-Team-6405e4d5014c0d0036e14f49/issues/superfluid-finance/superfluid-sentinel/237?planning-poker) with Zenhub @0xdavinchee @d10r @ngmachado

**Comment by d10r** [comment]
needs https://github.com/superfluid-finance/protocol-monorepo/issues/1675

**Comment by d10r** [comment]
Auto-generated activity started on avalanche-fuji.
Event `PoolCreated` in [this tx](https://testnet.snowtrace.io/address/0xa7f1a8204fd1a16b7ef8c5987c8cc4308a34ddfa) not picked up by subgraph, being investigated by @0xdavinchee 

cmd for activity generation:
```
POOL=0xA7F1A8204FD1A16b7EF8c5987C8cC4308a34dDfA RPC=https://avalanche-fuji.rpc.x.superfluid.dev SUPERTOKEN=0x24f3631dbbf6880C684c5e59578C21194e285Baf ACTION_INTERVAL=900 MINT_AMOUNT=10000 MIN_ETH_BALANCE="0.5" node app.js
```

first liquidation tx: https://testnet.snowtrace.io/tx/0xbd3226f5651ac1352692ed46e23d57231f112f764a92d6060c041d36091b69cf

**Comment by d10r** [comment]
script for activity generation: https://github.com/d10r/gda-activity

**Comment by d10r** [comment]
discovered another GDA subgraph issue

**Comment by hellwolf** [comment]
We are comfortable with manual testing without continuous testing setup. 

However, at the moment the previous run of manual testing discovered some errors.

**Comment by hellwolf** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2ZJIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a8ab311e77751467d3461c45c71b031c4c65d54b/image.png)

**Comment by hellwolf** [comment]
![image](https://github.com/superfluid-finance/superfluid-sentinel/assets/186660/b1bcf77b-dd32-4a5c-ba9e-6aac62c71943)

**Comment by hellwolf** [comment]
Waiting for sentinel PRs to be merged and do another round of test.

**Comment by elvijsTDL** [comment]
Testnet liquidations:
Avalanche-fuji: https://testnet.snowtrace.io/tx/0x32be04c22ead5b837481ffa06330b52096eb341c053ace2e5dd45b73712d6feb

**Comment by ngmachado** [comment]
This [PR](https://github.com/superfluid-finance/superfluid-sentinel/pull/257) will allow the sentinel to operate on Fuji until we fix the deployed GDA version. This is just a temporary fix and will be removed before any release.

**Comment by d10r** [comment]
checked with @elvijsTDL , we don't need to merge this. He'll use the branch for local testing and we can close the PR once fixed on protocol side.

**Comment by elvijsTDL** [comment]
✅ Version 9 and 10 sentinels were running fine on testnets
✅ Master branch sentinel ( GDA support ) was running fine on polygon-mainnet

GDA Liquidations on testnets:
[Arbitrum-Goerli](https://goerli.arbiscan.io/tx/0x8ce02f6d0f12ef5203cd06a327e5a6246401ec1f3415a36f62848b45e0b459df#eventlog)
[Optimism-Goerli](https://goerli-optimism.etherscan.io/tx/0x28aa143b27df79bbe384300bc45882b23c60195fca336e7784bf878f779fa18c#eventlog)
[Polygon-Mumbai](https://mumbai.polygonscan.com/tx/0x7722b86c715eb9d29e206bcb7fe07db184ea848d284141e126093bc267c701ff#eventlog)
[Avalanche-fuji](https://testnet.snowtrace.io/tx/0x32be04c22ead5b837481ffa06330b52096eb341c053ace2e5dd45b73712d6feb)
[Goerli](https://goerli.etherscan.io/tx/0x0523772a58782bfd7f9e0fa313d61a6b54703f5b6b748ce6dd9aa8bf67ed2b09#eventlog)
