### ISSUE TITLE
Complete GDA PR

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#245]
* Handle upgrading from pre-GDA instance
  * deal with pre-existing DB: if detecting old DB on start, exit and ask user to delete DB (or set env var `WIPE_INCOMPATIBLE_DB` signalling the application it is allowed to delete it itself)
  * don't fast-sync from incompatible snapshot
    * check the schema-version in `manifest,json`. If mismatch, don't use the manifest file fetched from github, but fall back to the bundled one.
    * snapshot generation: switch to generating v3 snapshots once the gda branch was merged (outside of this PR)
*  Compatibility with pre-GDA protocol deployment
  * On sentinel start, check if GDA is available and activate GDA functionality only if so.

**Comment by d10r** [comment]
since the DB needs to be wiped anyway, we have the unique opportunity to change the default DB location. I suggest we change it to data/db-<chainId>.sqlite. That way multi-network operation doesn't come with the hazard of DB clashes when leaving the default config and setting only the RPC env var.

@ngmachado do you see any disadvantage to doing that?

**Comment by ngmachado** [comment]
You mean the file being rename to db-{network}.sql right? I don't see problem with the change. For normal sentinel operators should be the same.

**Comment by hellwolf** [comment]
There are two PRs:

https://github.com/superfluid-finance/superfluid-sentinel/pull/243
&
https://github.com/superfluid-finance/superfluid-sentinel/pull/239

Close the one that's stale.

**Comment by hellwolf** [comment]
#243 is the duplicate and has been closed.

Waiting the work to be continued from #239

**Comment by hellwolf** [comment]
done.
