### ISSUE TITLE
[SENTINEL] Check sender balance only once per block

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#246]
When multiple outgoing streams are open, don't query sender balance once for each of them.

**Comment by ngmachado** [comment]
This issue happens from the current queue system where each task is processed separately. 

I'm hesitant to implement logic that stop estimations based on individual block numbers. This approach would introduce more complexity and we still end up making multiple checks to RPC.

**Deduplicating tasks within the queues.** For example, if an account/token is already queued for estimation, we shouldn't add another estimation for that same account/token."
