### ISSUE TITLE
[SENTINEL] Generate snapshots for gda-enabled sentinels (schema v3)

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#248]
Once https://github.com/superfluid-finance/superfluid-sentinel/pull/239 is merged, snapshots need to be generated for the new DB schema.
To be synced with increasing `schema-version` in `manifest.json` to 3.

**Comment by d10r** [comment]
related to https://github.com/superfluid-finance/superfluid-stories/issues/262

**Comment by ngmachado** [comment]
Sentinel as now the concept of schema version.

If mismatch we try using local version. 
If not possible we alert the user and stop the sentinel.
