### ISSUE TITLE
[SENTINEL] - Ensure proper queue Shutdown on Sentinel termination

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/superfluid-sentinel#255]
When we signal the sentinel to shutdown, we need to stop all concurrency tasks running. This is manly done, but we also need to take care of shutting down the estimations and agreement queues.

### Objective

The correct behaviour of sentinel when receiving a shutdown signal is to halt many of its tasks but we are not ensuring a full shutdown of `estimation` and `agreement`.

- [x] We should signal to queues that should end the correct tasks in hand 
- [x] Refuse new tasks to queue
- [x] Log as part of shutdown flow
- [x] Add tests

**Comment by philipandersson** [comment]
Ready for review
