### ISSUE TITLE
Support different repeatable launch setup files for the agent

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-sentinel#38]
As system admins, we are pro choices in what launch setup we use for the agent softwares.

## Notes

Must:

- [Containerzie the main agent software](#30)
- [Add health check endpoint to the agent itself ( /health HTTP endpoint )](#29)

Choices:

- [Read the README documentation of how to run the agent from scratch](#20)
- [Docker environment (docker-compose file)](#30)
- [HashiCorp-enabled Cloud environment ( terraform + nomad configurations )](https://github.com/superfluid-finance/metastructure/issues/36)

Future ideas:

- General Cloud Provider Support ( Using Packer, Ubuntu + systemd setup )
- Barebone Linux machine ( Systemd setup script, plus an Ansible role )

**Comment by ngmachado** [comment]
We support Docker and also shipped with a health check endpoint
