### ISSUE TITLE
DB path from cmdline is ignored

### ISSUE THREAD

**Issue by d10r** [superfluid-finance/superfluid-sentinel#44]
https://github.com/superfluid-finance/community-solvency-agent/blob/f18012855e4877b4bcdc1102a764993a9e64cba0/src/database/db.js#L3

Checks the env var and falls back to its own default if not set.  
Should instead use the value in app.config.

**Comment by ngmachado** [comment]
Its was related with the package-lock file right?

Can we closed it?
