### ISSUE TITLE
[SOLVENCY-AGENT] Liquidation preference

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-sentinel#5]
Implement "Liquidation preference" to mitigate theoretical high load:
    - High value streams (in terms of flow rate)
    - Closer to the liquidation date (more rewards to be collected)
    - Factoring the $ value of the assets.

**Comment by ngmachado** [comment]
ref: https://github.com/superfluid-finance/superfluid-sentinel/issues/165

**Comment by ngmachado** [comment]
This issue was superseded by a discussion on https://github.com/superfluid-finance/protocol-monorepo/discussions/1295
