### ISSUE TITLE
Define and create workflows for the branch and release policy

### ISSUE THREAD

**Issue by hellwolf** [superfluid-finance/superfluid-sentinel#68]
## Things can be done

- [x] Create protected branches, and define branch policy.
- [x] Create binaries and attach the a draft release note.
- [x] Create docker images and publish it to docker.io.
- [ ] ...

## Notes

Re release notes, please apply the same style as in https://github.com/superfluid-finance/protocol-monorepo/releases/tag/subgraph%40v1.1.0

**Comment by ngmachado** [comment]
@hellwolf this issue can be closed
