### ISSUE TITLE
In bootstart phase - don't clean DB

### ISSUE THREAD

**Issue by ngmachado** [superfluid-finance/superfluid-sentinel#81]
As of now, when booting the sentinel we are trying to clean the database from zombie rows (senders without active flows).

This process is starting to take large amount of time delaying the sync of sentinel. We can postpone this job to the liquidation logic that check if can perform the liquidation.

At this phase we can live with a less optimal storage size (database) in opposition of delaying the boot.

One solution is to create a background job that is responsible to maintain the database size in check.

**Comment by ngmachado** [comment]
related to: speed-up bootstrapping  #88

**Comment by d10r** [comment]
imo this has become a non-issue after solving https://github.com/superfluid-finance/superfluid-sentinel/issues/88  
Lets reopen if that turns out to be wrong / changes in the future.
